package crazyores_core.common.blocks;

import crazyores_core.common.core.COData;

public class BlockNames
{
	public static final String
	CO_PREFIX = COData.modID + ":",
	
	// Standard names. Used when registering blocks, so commands like /give will be easier to use in future updates.
	METEORITE_ORE = "meteorite_ore",
	COPPER_ORE = "copper_ore",
	SAPPHIRE_ORE = "sapphire_ore",
	ADAMITE_ORE = "adamite_ore",
	RUBY_ORE = "ruby_ore",
	FOOLS_RUBY_ORE = "fools_ruby_ore",
	ZECTIUM_ORE = "zectium_ore",
	TAPAZITE_ORE = "tapazite_ore",
	CRYSTAL_ORE = "crystal_ore",
	OSMONIUM_ORE = "osmonium_ore",
	STARCONIUM_ORE = "starconium_ore",
	EXPERIUM_ORE = "experium_ore",
	DEMONITE_STONE = "demonite_stone",
	INVISIUM_ORE = "invisium_ore",
	DARKSTONE = "darkstone",
	LUMINITE_ORE = "luminite_ore",
	ENDER_ORE = "ender_ore",
	ULTRA_ORE = "ultra_ore",
	
	METEORITE_BLOCK = "meteorite_block",
	GLOWING_METEORITE_BLOCK = "glowing_meteorite_block",
	COPPER_BLOCK = "copper_block",
	SAPPHIRE_BLOCK = "sapphire_block",
	ADAMITE_BLOCK = "adamite_block",
	RUBY_BLOCK = "ruby_block",
	FOOLS_RUBY_BLOCK = "fools_ruby_block",
	ZECTIUM_BLOCK = "zectium_block",
	TAPAZITE_BLOCK = "tapazite_block",
	CRYSTAL_BLOCK = "crystal_block",
	OSMONIUM_BLOCK = "osmonium_block",
	STARCONIUM_BLOCK = "starconium_block",
	DEMONITE_BLOCK = "demonite_block",
	REFINED_DEMONITE_BLOCK = "refined_demonite_block",
	INVISIUM_BLOCK = "invisium_block",
	ENDER_BLOCK = "ender_block",
	EXPERIUM_BLOCK = "experium_block",
	ULTRA_BLOCK = "ultra_block",
	
	COPPER_GOLEM_HEAD = "copper_golem_head",
	SAPPHIRE_GOLEM_HEAD = "sapphire_golem_head",
	ADAMITE_GOLEM_HEAD = "adamite_golem_head",
	RUBY_GOLEM_HEAD = "ruby_golem_head",
	FOOLS_RUBY_GOLEM_HEAD = "fools_ruby_golem_head",
	ZECTIUM_GOLEM_HEAD = "zectium_golem_head",
	TAPAZITE_GOLEM_HEAD = "tapazite_golem_head",
	CRYSTAL_GOLEM_HEAD = "crystal_golem_head",
	OSMONIUM_GOLEM_HEAD = "osmonium_golem_head",
	STARCONIUM_GOLEM_HEAD = "starconium_golem_head",
	DEMONITE_GOLEM_HEAD = "demonite_golem_head",
	
	DEMONITE_FURNACE = "demonite_furnace",
	LIT_DEMONITE_FURNACE = "lit_demonite_furnace",
	
	// Names with prefix. Used so Forge can read images. Also used as unlocalized names.
	METEORITE_ORE_PATH = CO_PREFIX + "meteorite_ore",
	COPPER_ORE_PATH = CO_PREFIX + "copper_ore",
	SAPPHIRE_ORE_PATH = CO_PREFIX + "sapphire_ore",
	ADAMITE_ORE_PATH = CO_PREFIX + "adamite_ore",
	RUBY_ORE_PATH = CO_PREFIX + "ruby_ore",
	FOOLS_RUBY_ORE_PATH = CO_PREFIX + "fools_ruby_ore",
	ZECTIUM_ORE_PATH = CO_PREFIX + "zectium_ore",
	TAPAZITE_ORE_PATH = CO_PREFIX + "tapazite_ore",
	CRYSTAL_ORE_PATH = CO_PREFIX + "crystal_ore",
	OSMONIUM_ORE_PATH = CO_PREFIX + "osmonium_ore",
	STARCONIUM_ORE_PATH = CO_PREFIX + "starconium_ore",
	EXPERIUM_ORE_PATH = CO_PREFIX + "experium_ore",
	DEMONITE_STONE_PATH = CO_PREFIX + "demonite_stone",
	INVISIUM_ORE_PATH = CO_PREFIX + "invisium_ore",
	DARKSTONE_PATH = CO_PREFIX + "darkstone",
	LUMINITE_ORE_PATH = CO_PREFIX + "luminite_ore",
	ENDER_ORE_PATH = CO_PREFIX + "ender_ore",
	ULTRA_ORE_PATH = CO_PREFIX + "ultra_ore",
	
	METEORITE_BLOCK_PATH = CO_PREFIX + "meteorite_block",
	GLOWING_METEORITE_BLOCK_PATH = CO_PREFIX + "glowing_meteorite_block",
	COPPER_BLOCK_PATH = CO_PREFIX + "copper_block",
	SAPPHIRE_BLOCK_PATH = CO_PREFIX + "sapphire_block",
	ADAMITE_BLOCK_PATH = CO_PREFIX + "adamite_block",
	RUBY_BLOCK_PATH = CO_PREFIX + "ruby_block",
	FOOLS_RUBY_BLOCK_PATH = CO_PREFIX + "fools_ruby_block",
	ZECTIUM_BLOCK_PATH = CO_PREFIX + "zectium_block",
	TAPAZITE_BLOCK_PATH = CO_PREFIX + "tapazite_block",
	CRYSTAL_BLOCK_PATH = CO_PREFIX + "crystal_block",
	OSMONIUM_BLOCK_PATH = CO_PREFIX + "osmonium_block",
	STARCONIUM_BLOCK_PATH = CO_PREFIX + "starconium_block",
	DEMONITE_BLOCK_PATH = CO_PREFIX + "demonite_block",
	REFINED_DEMONITE_BLOCK_PATH = CO_PREFIX + "refined_demonite_block",
	INVISIUM_BLOCK_PATH = CO_PREFIX + "invisium_block",
	ENDER_BLOCK_PATH = CO_PREFIX + "ender_block",
	EXPERIUM_BLOCK_PATH = CO_PREFIX + "experium_block",
	ULTRA_BLOCK_PATH = CO_PREFIX + "ultra_block",
	
	COPPER_GOLEM_HEAD_PATH = CO_PREFIX + "copper_golem_head",
	SAPPHIRE_GOLEM_HEAD_PATH = CO_PREFIX + "sapphire_golem_head",
	ADAMITE_GOLEM_HEAD_PATH = CO_PREFIX + "adamite_golem_head",
	RUBY_GOLEM_HEAD_PATH = CO_PREFIX + "ruby_golem_head",
	FOOLS_RUBY_GOLEM_HEAD_PATH = CO_PREFIX + "fools_ruby_golem_head",
	ZECTIUM_GOLEM_HEAD_PATH = CO_PREFIX + "zectium_golem_head",
	TAPAZITE_GOLEM_HEAD_PATH = CO_PREFIX + "tapazite_golem_head",
	CRYSTAL_GOLEM_HEAD_PATH = CO_PREFIX + "crystal_golem_head",
	OSMONIUM_GOLEM_HEAD_PATH = CO_PREFIX + "osmonium_golem_head",
	STARCONIUM_GOLEM_HEAD_PATH = CO_PREFIX + "starconium_golem_head",
	DEMONITE_GOLEM_HEAD_PATH = CO_PREFIX + "demonite_golem_head",
	
	DEMONITE_FURNACE_PATH = CO_PREFIX + "demonite_furnace",
	LIT_DEMONITE_FURNACE_PATH = CO_PREFIX + "lit_demonite_furnace",
	DEMONITE_FURNACE_SIDE_PATH = CO_PREFIX + "demonite_furnace_side",
	DEMONITE_FURNACE_TOP_PATH = CO_PREFIX + "demonite_furnace_top";
}
