package crazyores_core.common.items;

import crazyores_core.common.core.COData;

public class ItemNames
{
	public static final String
	CO_PREFIX = COData.modID + ":",
	
	// Standard names. Used when registering items, so commands like /give will be easier to use in future updates.
	METEORITE_COAL = "meteorite_coal",
	METEORITE_GEM = "meteorite_gem",
	COPPER_INGOT = "copper_ingot",
	SAPPHIRE_GEM = "sapphire_gem",
	ADAMITE_SHARD = "adamite_shard",
	RUBY_GEM = "ruby_gem",
	FOOLS_RUBY_GEM = "fools_ruby_gem",
	ZECTIUM_INGOT = "zectium_ingot",
	TAPAZITE_GEM = "tapazite_gem",
	CRYSTAL_SHARD = "crystal_shard",
	OSMONIUM_INGOT = "osmonium_ingot",
	STARCONIUM_GEM = "starconium_gem",
	FOOLS_RUBY_MUSH = "fools_ruby_mush",
	DEMONITE_ORB = "demonite_orb",
	EXPERIUM_ORB = "experium_orb",
	ENDER_GEM = "ender_gem",
	DARKSTONE_INGOT = "darkstone_ingot",
	INVISIUM_INGOT = "invisium_ingot",
	ULTRA_GEM = "ultra_gem",
	WHITE_LUMINITE_CRYSTAL = "white_luminite_crystal",
	
	METEORITE_PICKAXE = "meteorite_pickaxe",
	COPPER_PICKAXE = "copper_pickaxe",
	SAPPHIRE_PICKAXE = "sapphire_pickaxe",
	ADAMITE_PICKAXE = "adamite_pickaxe",
	RUBY_PICKAXE = "ruby_pickaxe",
	ZECTIUM_PICKAXE = "zectium_pickaxe",
	TAPAZITE_PICKAXE = "tapazite_pickaxe",
	CRYSTAL_PICKAXE = "crystal_pickaxe",
	OSMONIUM_PICKAXE = "osmonium_pickaxe",
	STARCONIUM_PICKAXE = "starconium_pickaxe",
	INVISIUM_PICKAXE = "invisium_pickaxe",
	ENDER_PICKAXE = "ender_pickaxe",
	
	METEORITE_AXE = "meteorite_axe",
	COPPER_AXE = "copper_axe",
	SAPPHIRE_AXE = "sapphire_axe",
	ADAMITE_AXE = "adamite_axe",
	RUBY_AXE = "ruby_axe",
	ZECTIUM_AXE = "zectium_axe",
	TAPAZITE_AXE = "tapazite_axe",
	CRYSTAL_AXE = "crystal_axe",
	OSMONIUM_AXE = "osmonium_axe",
	STARCONIUM_AXE = "starconium_axe",
	INVISIUM_AXE = "invisium_axe",
	ENDER_AXE = "ender_axe",
	
	METEORITE_SHOVEL = "meteorite_shovel",
	COPPER_SHOVEL = "copper_shovel",
	SAPPHIRE_SHOVEL = "sapphire_shovel",
	ADAMITE_SHOVEL = "adamite_shovel",
	RUBY_SHOVEL = "ruby_shovel",
	ZECTIUM_SHOVEL = "zectium_shovel",
	TAPAZITE_SHOVEL = "tapazite_shovel",
	CRYSTAL_SHOVEL = "crystal_shovel",
	OSMONIUM_SHOVEL = "osmonium_shovel",
	STARCONIUM_SHOVEL = "starconium_shovel",
	INVISIUM_SHOVEL = "invisium_shovel",
	ENDER_SHOVEL = "ender_shovel",
	
	METEORITE_SWORD = "meteorite_sword",
	COPPER_SWORD = "copper_sword",
	SAPPHIRE_SWORD = "sapphire_sword",
	ADAMITE_SWORD = "adamite_sword",
	RUBY_SWORD = "ruby_sword",
	ZECTIUM_SWORD = "zectium_sword",
	TAPAZITE_SWORD = "tapazite_sword",
	CRYSTAL_SWORD = "crystal_sword",
	OSMONIUM_SWORD = "osmonium_sword",
	STARCONIUM_SWORD = "starconium_sword",
	INVISIUM_SWORD = "invisium_sword",
	ENDER_SWORD = "ender_sword",

	METEORITE_HOE = "meteorite_hoe",
	COPPER_HOE = "copper_hoe",
	SAPPHIRE_HOE = "sapphire_hoe",
	ADAMITE_HOE = "adamite_hoe",
	RUBY_HOE = "ruby_hoe",
	ZECTIUM_HOE = "zectium_hoe",
	TAPAZITE_HOE = "tapazite_hoe",
	CRYSTAL_HOE = "crystal_hoe",
	OSMONIUM_HOE = "osmonium_hoe",
	STARCONIUM_HOE = "starconium_hoe",
	INVISIUM_HOE = "invisium_hoe",
	ENDER_HOE = "ender_hoe",
	
	STARCONIUM_SLEDGEHAMMER = "starconium_sledgehammer",
	
	COPPER_HELMET = "copper_helmet",
	SAPPHIRE_HELMET = "sapphire_helmet",
	ADAMITE_HELMET = "adamite_helmet",
	METEORITE_HELMET = "meteorite_helmet",
	RUBY_HELMET = "ruby_helmet",
	ZECTIUM_HELMET = "zectium_helmet",
	TAPAZITE_HELMET = "tapazite_helmet",
	CRYSTAL_HELMET = "crystal_helmet",
	OSMONIUM_HELMET = "osmonium_helmet",
	STARCONIUM_HELMET = "starconium_helmet",
	INVISIUM_HELMET = "invisium_helmet",
	ENDER_HELMET = "ender_helmet",
	
	COPPER_CHESTPLATE = "copper_chestplate",
	SAPPHIRE_CHESTPLATE = "sapphire_chestplate",
	ADAMITE_CHESTPLATE = "adamite_chestplate",
	METEORITE_CHESTPLATE = "meteorite_chestplate",
	RUBY_CHESTPLATE = "ruby_chestplate",
	ZECTIUM_CHESTPLATE = "zectium_chestplate",
	TAPAZITE_CHESTPLATE = "tapazite_chestplate",
	CRYSTAL_CHESTPLATE = "crystal_chestplate",
	OSMONIUM_CHESTPLATE = "osmonium_chestplate",
	STARCONIUM_CHESTPLATE = "starconium_chestplate",
	INVISIUM_CHESTPLATE = "invisium_chestplate",
	ENDER_CHESTPLATE = "ender_chestplate",
	
	COPPER_LEGGINGS = "copper_leggings",
	SAPPHIRE_LEGGINGS = "sapphire_leggings",
	ADAMITE_LEGGINGS = "adamite_leggings",
	METEORITE_LEGGINGS = "meteorite_leggings",
	RUBY_LEGGINGS = "ruby_leggings",
	ZECTIUM_LEGGINGS = "zectium_leggings",
	TAPAZITE_LEGGINGS = "tapazite_leggings",
	CRYSTAL_LEGGINGS = "crystal_leggings",
	OSMONIUM_LEGGINGS = "osmonium_leggings",
	STARCONIUM_LEGGINGS = "starconium_leggings",
	INVISIUM_LEGGINGS = "invisium_leggings",
	ENDER_LEGGINGS = "ender_leggings",
	
	COPPER_BOOTS = "copper_boots",
	SAPPHIRE_BOOTS = "sapphire_boots",
	ADAMITE_BOOTS = "adamite_boots",
	METEORITE_BOOTS = "meteorite_boots",
	RUBY_BOOTS = "ruby_boots",
	ZECTIUM_BOOTS = "zectium_boots",
	TAPAZITE_BOOTS = "tapazite_boots",
	CRYSTAL_BOOTS = "crystal_boots",
	OSMONIUM_BOOTS = "osmonium_boots",
	STARCONIUM_BOOTS = "starconium_boots",
	INVISIUM_BOOTS = "invisium_boots",
	ENDER_BOOTS = "ender_boots",
	
	COPPER_BUCKET_EMPTY = "copper_bucket_empty",
	COPPER_BUCKET_WATER = "copper_bucket_water",
	COPPER_BUCKET_LAVA = "copper_bucket_lava",
	
	STARCONIUM_SHARD = "starconium_shard",
	
	COPPER_ROD = "copper_rod",
	SAPPHIRE_ROD = "sapphire_rod",
	ADAMITE_ROD = "adamite_rod",
	METEORITE_ROD = "meteorite_rod",
	RUBY_ROD = "ruby_rod",
	ZECTIUM_ROD = "zectium_rod",
	TAPAZITE_ROD = "tapazite_rod",
	CRYSTAL_ROD = "crystal_rod",
	OSMONIUM_ROD = "osmonium_rod",
	STARCONIUM_ROD = "starconium_rod",
	INVISIUM_ROD = "invisium_rod",
	ENDER_ROD = "ender_rod",
	
	METEORITE_BOW = "meteorite_bow",
	COPPER_BOW = "copper_bow",
	INVISIUM_BOW = "invisium_bow",
	SAPPHIRE_BOW = "sapphire_bow",
	ADAMITE_BOW = "adamite_bow",
	RUBY_BOW = "ruby_bow",
	ZECTIUM_BOW = "zectium_bow",
	TAPAZITE_BOW = "tapazite_bow",
	CRYSTAL_BOW = "crystal_bow",
	OSMONIUM_BOW = "osmonium_bow",
	ENDER_BOW = "ender_bow",
	STARCONIUM_BOW = "starconium_bow",
	
	METEORITE_ARROW = "meteorite_arrow",
	COPPER_ARROW = "copper_arrow",
	INVISIUM_ARROW = "invisium_arrow",
	SAPPHIRE_ARROW = "sapphire_arrow",
	ADAMITE_ARROW = "adamite_arrow",
	RUBY_ARROW = "ruby_arrow",
	ZECTIUM_ARROW = "zectium_arrow",
	TAPAZITE_ARROW = "tapazite_arrow",
	CRYSTAL_ARROW = "crystal_arrow",
	OSMONIUM_ARROW = "osmonium_arrow",
	ENDER_ARROW = "ender_arrow",
	STARCONIUM_ARROW = "starconium_arrow",
	
	// Names with prefix. Used so Forge can read images. Also used as unlocalized names.
	METEORITE_COAL_PATH = CO_PREFIX + "meteorite_coal",
	METEORITE_GEM_PATH = CO_PREFIX + "meteorite_gem",
	COPPER_INGOT_PATH = CO_PREFIX + "copper_ingot",
	SAPPHIRE_GEM_PATH = CO_PREFIX + "sapphire_gem",
	ADAMITE_SHARD_PATH = CO_PREFIX + "adamite_shard",
	RUBY_GEM_PATH = CO_PREFIX + "ruby_gem",
	FOOLS_RUBY_GEM_PATH = CO_PREFIX + "fools_ruby_gem",
	ZECTIUM_INGOT_PATH = CO_PREFIX + "zectium_ingot",
	TAPAZITE_GEM_PATH = CO_PREFIX + "tapazite_gem",
	CRYSTAL_SHARD_PATH = CO_PREFIX + "crystal_shard",
	OSMONIUM_INGOT_PATH = CO_PREFIX + "osmonium_ingot",
	STARCONIUM_GEM_PATH = CO_PREFIX + "starconium_gem",
	FOOLS_RUBY_MUSH_PATH = CO_PREFIX + "fools_ruby_mush",
	DEMONITE_ORB_PATH = CO_PREFIX + "demonite_orb",
	EXPERIUM_ORB_PATH = CO_PREFIX + "experium_orb",
	ENDER_GEM_PATH = CO_PREFIX + "ender_gem",
	DARKSTONE_INGOT_PATH = CO_PREFIX + "darkstone_ingot",
	INVISIUM_INGOT_PATH = CO_PREFIX + "invisium_ingot",
	ULTRA_GEM_PATH = CO_PREFIX + "ultra_gem",
	WHITE_LUMINITE_CRYSTAL_PATH = CO_PREFIX + "white_luminite_crystal",
	
	METEORITE_PICKAXE_PATH = CO_PREFIX + "meteorite_pickaxe",
	COPPER_PICKAXE_PATH = CO_PREFIX + "copper_pickaxe",
	SAPPHIRE_PICKAXE_PATH = CO_PREFIX + "sapphire_pickaxe",
	ADAMITE_PICKAXE_PATH = CO_PREFIX + "adamite_pickaxe",
	RUBY_PICKAXE_PATH = CO_PREFIX + "ruby_pickaxe",
	ZECTIUM_PICKAXE_PATH = CO_PREFIX + "zectium_pickaxe",
	TAPAZITE_PICKAXE_PATH = CO_PREFIX + "tapazite_pickaxe",
	CRYSTAL_PICKAXE_PATH = CO_PREFIX + "crystal_pickaxe",
	OSMONIUM_PICKAXE_PATH = CO_PREFIX + "osmonium_pickaxe",
	STARCONIUM_PICKAXE_PATH = CO_PREFIX + "starconium_pickaxe",
	INVISIUM_PICKAXE_PATH = CO_PREFIX + "invisium_pickaxe",
	ENDER_PICKAXE_PATH = CO_PREFIX + "ender_pickaxe",
	
	METEORITE_AXE_PATH = CO_PREFIX + "meteorite_axe",
	COPPER_AXE_PATH = CO_PREFIX + "copper_axe",
	SAPPHIRE_AXE_PATH = CO_PREFIX + "sapphire_axe",
	ADAMITE_AXE_PATH = CO_PREFIX + "adamite_axe",
	RUBY_AXE_PATH = CO_PREFIX + "ruby_axe",
	ZECTIUM_AXE_PATH = CO_PREFIX + "zectium_axe",
	TAPAZITE_AXE_PATH = CO_PREFIX + "tapazite_axe",
	CRYSTAL_AXE_PATH = CO_PREFIX + "crystal_axe",
	OSMONIUM_AXE_PATH = CO_PREFIX + "osmonium_axe",
	STARCONIUM_AXE_PATH = CO_PREFIX + "starconium_axe",
	INVISIUM_AXE_PATH = CO_PREFIX + "invisium_axe",
	ENDER_AXE_PATH = CO_PREFIX + "ender_axe",
	
	METEORITE_SHOVEL_PATH = CO_PREFIX + "meteorite_shovel",
	COPPER_SHOVEL_PATH = CO_PREFIX + "copper_shovel",
	SAPPHIRE_SHOVEL_PATH = CO_PREFIX + "sapphire_shovel",
	ADAMITE_SHOVEL_PATH = CO_PREFIX + "adamite_shovel",
	RUBY_SHOVEL_PATH = CO_PREFIX + "ruby_shovel",
	ZECTIUM_SHOVEL_PATH = CO_PREFIX + "zectium_shovel",
	TAPAZITE_SHOVEL_PATH = CO_PREFIX + "tapazite_shovel",
	CRYSTAL_SHOVEL_PATH = CO_PREFIX + "crystal_shovel",
	OSMONIUM_SHOVEL_PATH = CO_PREFIX + "osmonium_shovel",
	STARCONIUM_SHOVEL_PATH = CO_PREFIX + "starconium_shovel",
	INVISIUM_SHOVEL_PATH = CO_PREFIX + "invisium_shovel",
	ENDER_SHOVEL_PATH = CO_PREFIX + "ender_shovel",
	
	METEORITE_SWORD_PATH = CO_PREFIX + "meteorite_sword",
	COPPER_SWORD_PATH = CO_PREFIX + "copper_sword",
	SAPPHIRE_SWORD_PATH = CO_PREFIX + "sapphire_sword",
	ADAMITE_SWORD_PATH = CO_PREFIX + "adamite_sword",
	RUBY_SWORD_PATH = CO_PREFIX + "ruby_sword",
	ZECTIUM_SWORD_PATH = CO_PREFIX + "zectium_sword",
	TAPAZITE_SWORD_PATH = CO_PREFIX + "tapazite_sword",
	CRYSTAL_SWORD_PATH = CO_PREFIX + "crystal_sword",
	OSMONIUM_SWORD_PATH = CO_PREFIX + "osmonium_sword",
	STARCONIUM_SWORD_PATH = CO_PREFIX + "starconium_sword",
	INVISIUM_SWORD_PATH = CO_PREFIX + "invisium_sword",
	ENDER_SWORD_PATH = CO_PREFIX + "ender_sword",

	METEORITE_HOE_PATH = CO_PREFIX + "meteorite_hoe",
	COPPER_HOE_PATH = CO_PREFIX + "copper_hoe",
	SAPPHIRE_HOE_PATH = CO_PREFIX + "sapphire_hoe",
	ADAMITE_HOE_PATH = CO_PREFIX + "adamite_hoe",
	RUBY_HOE_PATH = CO_PREFIX + "ruby_hoe",
	ZECTIUM_HOE_PATH = CO_PREFIX + "zectium_hoe",
	TAPAZITE_HOE_PATH = CO_PREFIX + "tapazite_hoe",
	CRYSTAL_HOE_PATH = CO_PREFIX + "crystal_hoe",
	OSMONIUM_HOE_PATH = CO_PREFIX + "osmonium_hoe",
	STARCONIUM_HOE_PATH = CO_PREFIX + "starconium_hoe",
	INVISIUM_HOE_PATH = CO_PREFIX + "invisium_hoe",
	ENDER_HOE_PATH = CO_PREFIX + "ender_hoe",
	
	STARCONIUM_SLEDGEHAMMER_PATH = CO_PREFIX + "starconium_sledgehammer",
	
	COPPER_HELMET_PATH = CO_PREFIX + "copper_helmet",
	SAPPHIRE_HELMET_PATH = CO_PREFIX + "sapphire_helmet",
	ADAMITE_HELMET_PATH = CO_PREFIX + "adamite_helmet",
	METEORITE_HELMET_PATH = CO_PREFIX + "meteorite_helmet",
	RUBY_HELMET_PATH = CO_PREFIX + "ruby_helmet",
	ZECTIUM_HELMET_PATH = CO_PREFIX + "zectium_helmet",
	TAPAZITE_HELMET_PATH = CO_PREFIX + "tapazite_helmet",
	CRYSTAL_HELMET_PATH = CO_PREFIX + "crystal_helmet",
	OSMONIUM_HELMET_PATH = CO_PREFIX + "osmonium_helmet",
	STARCONIUM_HELMET_PATH = CO_PREFIX + "starconium_helmet",
	INVISIUM_HELMET_PATH = CO_PREFIX + "invisium_helmet",
	ENDER_HELMET_PATH = CO_PREFIX + "ender_helmet",
	
	COPPER_CHESTPLATE_PATH = CO_PREFIX + "copper_chestplate",
	SAPPHIRE_CHESTPLATE_PATH = CO_PREFIX + "sapphire_chestplate",
	ADAMITE_CHESTPLATE_PATH = CO_PREFIX + "adamite_chestplate",
	METEORITE_CHESTPLATE_PATH = CO_PREFIX + "meteorite_chestplate",
	RUBY_CHESTPLATE_PATH = CO_PREFIX + "ruby_chestplate",
	ZECTIUM_CHESTPLATE_PATH = CO_PREFIX + "zectium_chestplate",
	TAPAZITE_CHESTPLATE_PATH = CO_PREFIX + "tapazite_chestplate",
	CRYSTAL_CHESTPLATE_PATH = CO_PREFIX + "crystal_chestplate",
	OSMONIUM_CHESTPLATE_PATH = CO_PREFIX + "osmonium_chestplate",
	STARCONIUM_CHESTPLATE_PATH = CO_PREFIX + "starconium_chestplate",
	INVISIUM_CHESTPLATE_PATH = CO_PREFIX + "invisium_chestplate",
	ENDER_CHESTPLATE_PATH = CO_PREFIX + "ender_chestplate",
	
	COPPER_LEGGINGS_PATH = CO_PREFIX + "copper_leggings",
	SAPPHIRE_LEGGINGS_PATH = CO_PREFIX + "sapphire_leggings",
	ADAMITE_LEGGINGS_PATH = CO_PREFIX + "adamite_leggings",
	METEORITE_LEGGINGS_PATH = CO_PREFIX + "meteorite_leggings",
	RUBY_LEGGINGS_PATH = CO_PREFIX + "ruby_leggings",
	ZECTIUM_LEGGINGS_PATH = CO_PREFIX + "zectium_leggings",
	TAPAZITE_LEGGINGS_PATH = CO_PREFIX + "tapazite_leggings",
	CRYSTAL_LEGGINGS_PATH = CO_PREFIX + "crystal_leggings",
	OSMONIUM_LEGGINGS_PATH = CO_PREFIX + "osmonium_leggings",
	STARCONIUM_LEGGINGS_PATH = CO_PREFIX + "starconium_leggings",
	INVISIUM_LEGGINGS_PATH = CO_PREFIX + "invisium_leggings",
	ENDER_LEGGINGS_PATH = CO_PREFIX + "ender_leggings",
	
	COPPER_BOOTS_PATH = CO_PREFIX + "copper_boots",
	SAPPHIRE_BOOTS_PATH = CO_PREFIX + "sapphire_boots",
	ADAMITE_BOOTS_PATH = CO_PREFIX + "adamite_boots",
	METEORITE_BOOTS_PATH = CO_PREFIX + "meteorite_boots",
	RUBY_BOOTS_PATH = CO_PREFIX + "ruby_boots",
	ZECTIUM_BOOTS_PATH = CO_PREFIX + "zectium_boots",
	TAPAZITE_BOOTS_PATH = CO_PREFIX + "tapazite_boots",
	CRYSTAL_BOOTS_PATH = CO_PREFIX + "crystal_boots",
	OSMONIUM_BOOTS_PATH = CO_PREFIX + "osmonium_boots",
	STARCONIUM_BOOTS_PATH = CO_PREFIX + "starconium_boots",
	INVISIUM_BOOTS_PATH = CO_PREFIX + "invisium_boots",
	ENDER_BOOTS_PATH = CO_PREFIX + "ender_boots",
	
	COPPER_BUCKET_EMPTY_PATH = CO_PREFIX + "copper_bucket_empty",
	COPPER_BUCKET_WATER_PATH = CO_PREFIX + "copper_bucket_water",
	COPPER_BUCKET_LAVA_PATH = CO_PREFIX + "copper_bucket_lava",
	
	STARCONIUM_SHARD_PATH = CO_PREFIX + "starconium_shard",
	
	COPPER_ROD_PATH = CO_PREFIX + "copper_rod",
	SAPPHIRE_ROD_PATH = CO_PREFIX + "sapphire_rod",
	ADAMITE_ROD_PATH = CO_PREFIX + "adamite_rod",
	METEORITE_ROD_PATH = CO_PREFIX + "meteorite_rod",
	RUBY_ROD_PATH = CO_PREFIX + "ruby_rod",
	ZECTIUM_ROD_PATH = CO_PREFIX + "zectium_rod",
	TAPAZITE_ROD_PATH = CO_PREFIX + "tapazite_rod",
	CRYSTAL_ROD_PATH = CO_PREFIX + "crystal_rod",
	OSMONIUM_ROD_PATH = CO_PREFIX + "osmonium_rod",
	STARCONIUM_ROD_PATH = CO_PREFIX + "starconium_rod",
	INVISIUM_ROD_PATH = CO_PREFIX + "invisium_rod",
	ENDER_ROD_PATH = CO_PREFIX + "ender_rod",
	
	METEORITE_BOW_PATH = CO_PREFIX + "meteorite_bow",
	COPPER_BOW_PATH = CO_PREFIX + "copper_bow",
	INVISIUM_BOW_PATH = CO_PREFIX + "invisium_bow",
	SAPPHIRE_BOW_PATH = CO_PREFIX + "sapphire_bow",
	ADAMITE_BOW_PATH = CO_PREFIX + "adamite_bow",
	RUBY_BOW_PATH = CO_PREFIX + "ruby_bow",
	ZECTIUM_BOW_PATH = CO_PREFIX + "zectium_bow",
	TAPAZITE_BOW_PATH = CO_PREFIX + "tapazite_bow",
	CRYSTAL_BOW_PATH = CO_PREFIX + "crystal_bow",
	OSMONIUM_BOW_PATH = CO_PREFIX + "osmonium_bow",
	ENDER_BOW_PATH = CO_PREFIX + "ender_bow",
	STARCONIUM_BOW_PATH = CO_PREFIX + "starconium_bow",
	
	METEORITE_ARROW_PATH = CO_PREFIX + "meteorite_arrow",
	COPPER_ARROW_PATH = CO_PREFIX + "copper_arrow",
	INVISIUM_ARROW_PATH = CO_PREFIX + "invisium_arrow",
	SAPPHIRE_ARROW_PATH = CO_PREFIX + "sapphire_arrow",
	ADAMITE_ARROW_PATH = CO_PREFIX + "adamite_arrow",
	RUBY_ARROW_PATH = CO_PREFIX + "ruby_arrow",
	ZECTIUM_ARROW_PATH = CO_PREFIX + "zectium_arrow",
	TAPAZITE_ARROW_PATH = CO_PREFIX + "tapazite_arrow",
	CRYSTAL_ARROW_PATH = CO_PREFIX + "crystal_arrow",
	OSMONIUM_ARROW_PATH = CO_PREFIX + "osmonium_arrow",
	ENDER_ARROW_PATH = CO_PREFIX + "ender_arrow",
	STARCONIUM_ARROW_PATH = CO_PREFIX + "starconium_arrow";
}
